name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main      # O workflow é acionado automaticamente
  workflow_dispatch:

permissions:
  contents: read  # Permite ler os arquivos do repositório.
  pages: write    # Permite escrever (atualizar) o conteúdo no GitHub Pages.
  id-token: write # Permite autenticação segura para ações do GitHub.

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4   # Clonar o repositório na máquina de execução.

      - name: Criar diretório de build
        run: |
          mkdir -p public/IHC
          mkdir -p public/ICG
          mkdir -p public/Labi

          # Copiar os ficheiros do IHC
          cp -r 3y/2s/IHC/PraticAssigment2/Theme/* public/IHC/

          # Copiar os ficheiros do ICG
          cp -r 3y/2s/ICG/Proj/* public/ICG/

          # Copiar os ficheiros do Labi
          cp -r 1y/Labi/1s/Proj2/* public/Labi/

          echo "Contents of public directory:"
          ls -R public

      - name: Verificar se os diretórios estão vazios
        run: |
          for dir in IHC ICG Labi; do
            if [ -z "$(ls -A public/$dir)" ]; then
              echo "Error: $dir directory is empty!"
              exit 1
            fi
          done

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload do artefato para o GitHub Pages
        uses: actions/upload-pages-artifact@v3  # para enviar a pasta public como um artefato que será usado para o deploy.
        with:
          path: ./public

      - name: Deploy para GitHub Pages
        uses: actions/deploy-pages@v4           # para publicar o site no GitHub Pages.
